modLoader = "javafml"
loaderVersion = "[46,)"
license = "All rights reserved"

[[mods]]
    modId = "subtle_effects"
    version = "${version}"
    displayName = "Subtle Effects"
    displayURL="https://curseforge.com/minecraft/mods/subtle-effects"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    issueTrackerURL="https://github.com/MincraftEinstein/SubtleEffects/issues"
    logoFile = "pack.png"
    credits = ""
    authors = "MincraftEinstein"
    description = '''
Adding many new subtle details through particles and a few sounds
'''

[[dependencies.subtle_effects]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.subtle_effects]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20, 1.21)"
    ordering = "NONE"
    side = "CLIENT"
